const UPDATE_SEARCH = {
    QUERY: 'UPDATE_SEARCH_QUERY',
    TOGGLE_TRUE: 'UPDATE_SEARCH_TOGGLE_TRUE',
    TOGGLE_FALSE: 'UPDATE_SEARCH_TOGGLE_FALSE',
    RESULTS: 'UPDATE_SEARCH_RESULTS',
    INDEX: 'UPDATE_SEARCH_INDEX',
};

const UPDATE_BLOG = {
  ARRAY: 'UPDATE_BLOG_ARRAY',
  MODAL: 'UPDATE_BLOG_MODAL',
  PAGE_NUMBER: 'UPDATE_PAGE_NUMBER',
  PAGE: 'UPDATE_BLOG_PAGE',
  DISPLAY: 'UPDATE_BLOG_DISPLAY',
  FORM: 'UPDATE_BLOG_FORM',
  SHOW_MODAL_TRUE: 'UPDATE_SHOW_MODAL_TRUE',
  SHOW_MODAL_FALSE:'UPDATE_SHOW_MODAL_FALSE',
  LOADING_TRUE: 'UPDATE_BLOG_LOADING_TRUE',
  LOADING_FALSE: 'UPDATE_BLOG_LOADING_FALSE',
  ERROR: 'UPDATE_BLOG_ERROR'
};

const UPDATE_FILTER = {
  FILTER_BUTTON: 'UPDATE_FILTER_BUTTON',
  FILTERS: 'UPDATE_FILTERS',
};

const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';

const UPDATE_PORTFOLIO = {
  ARRAY: 'UPDATE_PORTFOLIO_ARRAY',
  LOADING_TRUE: 'UPDATE_PORTFOLIO_LOADING_TRUE',
  LOADING_FALSE: 'UPDATE_PORTFOLIO_LOADING_TRUE',
  ERROR: 'UPDATE_PORTFOLIO_ERROR'
}

export {
  UPDATE_SEARCH,
  UPDATE_BLOG,
  UPDATE_FILTER,
  UPDATE_NOTIFICATION,
  UPDATE_PORTFOLIO
}
