import {
  fetchBlogs,
  newBlog,
  updateBlog,
  deleteBlog,
  fetchFilters,
  newFilter,
  updateFilter,
  deleteFilter,
  redirectPage,
  redirectNewBlogForm,
  updateSearchQuery,
  updateSearchToggle,
  updateSearchResults,
  updateSearchIndex,
  updateBlogArray,
  updateBlogModal,
  updatePageNumber,
  updateBlogPage,
  updateBlogsDisplay,
  updateFilterButton,
  updateFilters,
  updateNotification,
  updateBlogForm,
  updateShowModal
} from './actions/blog';

import rootReducer from './reducers/rootReducer'

import {
  getSearchQuery,
  getSearchToggle,
  getSearchResults,
  getSearchIndex,
  getBlogs,
  getBlogModal,
  getPages,
  getActivePage,
  getBlogsDisplay,
  getFilters,
  getFilterButton,
  getNotification,
  getBlogForm,
  getShowModal,
  getPathname
} from './selectors'

export {
  fetchBlogs,
  newBlog,
  updateBlog,
  deleteBlog,
  fetchFilters,
  newFilter,
  updateFilter,
  deleteFilter,
  redirectPage,
  redirectNewBlogForm,
  updateSearchQuery,
  updateSearchToggle,
  updateSearchResults,
  updateSearchIndex,
  updateBlogArray,
  updateBlogModal,
  updatePageNumber,
  updateBlogPage,
  updateBlogsDisplay,
  updateFilterButton,
  updateFilters,
  updateNotification,
  updateBlogForm,
  updateShowModal,
  rootReducer,
  getSearchQuery,
  getSearchToggle,
  getSearchResults,
  getSearchIndex,
  getBlogs,
  getBlogModal,
  getPages,
  getActivePage,
  getBlogsDisplay,
  getFilters,
  getFilterButton,
  getNotification,
  getBlogForm,
  getShowModal,
  getPathname
}